### ISSUE TITLE
UTF-8 support: ./bin/hsd-cli rpc getnameinfo foobar-ąčęėįšųūž-„mumble“

### ISSUE THREAD

**Issue by linas** [handshake-org/hs-client#33]
When I attempt 

`./bin/hsd-cli rpc getnameinfo foobar-ąčęėįšųūž-„mumble“` 

I get a reply `Invalid name.`  Any name that I try, containing any one of these letters, seems not to work. Yet, these names do seem to be valid when accessed via a block-explorer... Am I missing something, or is this a bug?

**Comment by pinheadmz** [comment]
I believe I answered you on IRC:

```
20:01  pinheadmz	https://www.punycoder.com/
20:01  pinheadmz	your weird looking domain is encoded as xn--foobar--mumble-hwb2k6g9a89ak7a9ftg3jk180eiba
20:01  pinheadmz	and (even without handshake) if you put http://foobar-ąčęėįšųūž-„mumble“ into chrome, it should reveal to you the actual encoding
20:01  pinheadmz	i.e. `http://xn--foobar--mumble-hwb2k6g9a89ak7a9ftg3jk180eiba/` 
20:01  pinheadmz	so that would be the actual name you would try to acquire on handshake
```

Other things to read up on: https://en.wikipedia.org/wiki/Fully_qualified_domain_name and the RFCs that are linked. In the DNS, only certain characters are allowed (numbers, letters, hyphens)

**Comment by linas** [comment]
Oh, Ah. So you're saying the API accepts punycode-only. OK.

In that case,  I guess this could be treated as an "enhancement request: "please automatically convert utf8 to punycode" but I can see that you might not want to do that.

OK Thanks!
