### ISSUE TITLE
hsw-cli sent HNS to two addresses?

### ISSUE THREAD

**Issue by retorquere** [handshake-org/hs-client#40]
I tried sending some HNS to another wallet as a test:

```
./bin/hsw-cli send --value=2 --address=hs1...
```

but hnscan.com lists two recipients it seems; one indeed the address I specified on the command line which received 2 HNS, but another one that I apparently transfered more than 4000 HNS to. What did I do wrong here?

**Comment by pinheadmz** [comment]
That's your change address. It's a very easy Bitcoin concept to search for and learn about, here's just one explanation:

https://coinguides.org/bitcoin-change-address-output/

**Comment by retorquere** [comment]
Thanks! Scared the bejeezus out of me. I will read up (entirely new to crypto currency), but is the gist of it "don't worry"?

**Comment by retorquere** [comment]
OK, I think I understand the concepts now, but how do I "claim" these change addresses so that I can spend from them?

**Comment by pinheadmz** [comment]
Yes don't worry ;-) your wallet will handle that for you automatically. You can check your balance with the command:

`hsw-cli rpc getbalance`

...and you should see what you expect.

I'm guessing you got your initial HNS from an airdrop claim, and received 4246.894314 HNS. So if that 2 HNS is the only transaction you have sent, you should have a balance of about 4244.894314 (less miner fees). Or if you sent that 2 HNS to your own wallet, your original balance will only be negligibly different. ("miner fees" are another basic Bitcoin concept you can easily learn about)

Money in Bitcoin and Handshake is based on "transaction outputs" aka "UTXO" or "coins". You can think of these objects like paper bills in a real world wallet in your pocket: There are a few pieces of paper, each with their own value and altogether that creates a wallet balance. If you pay for something with a $10 you may get a $5 and three $1's back. So your total balance is deducted by two dollars but the contents of your wallet have gone from one piece of paper to four.

**Comment by retorquere** [comment]
Awesome. I think I have a better picture now, and together with your explanation, the transaction history now makes sense.

Yep, airdrop recipient, and very much my first contact with crypto currency. Thanks for the explanation!
